// Shared presentation only: calculation and export approval stay with each report.
export const reportEscape = (value: unknown) => String(value ?? '')
  .replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;')
  .replaceAll('"', '&quot;').replaceAll("'", '&#039;');

type ReportSection = { title: string; description: string; content: string };
type ReportDocument = {
  title: string; subtitle: string; status: string;
  tone: 'good' | 'caution' | 'danger' | 'neutral';
  summary: string; sections: ReportSection[]; footer: string; watermark?: string;
};

export function reportTable(label: string, table: string) {
  return `<div class="report-table-scroll" role="region" aria-label="${reportEscape(label)}" tabindex="0">${table}</div>`;
}

export const REPORT_SIGNOFF = `<div class="report-signoff"><div><span>작업 담당</span><b>성명 / 서명</b></div><div><span>검토 담당</span><b>성명 / 서명</b></div><div><span>확인 일시</span><b>년　　 월　　 일　　 시</b></div></div>`;

export const REPORT_CSS = `
@page{size:A4 portrait;margin:12mm}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#f5f5f7;color:#1d1d1f;font:14px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI","Malgun Gothic",sans-serif;-webkit-print-color-adjust:exact;print-color-adjust:exact}h1,h2,h3,p{margin:0}a{color:inherit}button{font:inherit}b,strong{font-weight:650}svg{max-width:100%}
.report-toolbar{max-width:1000px;margin:20px auto 12px;padding:0 8px;display:flex;justify-content:space-between;align-items:center;gap:12px;color:#6e6e73;font-size:12px}.report-toolbar div{display:flex;gap:8px}.report-toolbar button{border:1px solid #d2d2d7;border-radius:10px;background:#fff;padding:9px 16px;cursor:pointer;color:#1d1d1f}.report-toolbar .print{background:#0071e3;border-color:#0071e3;color:#fff}.report-toolbar button:hover{filter:brightness(.96)}:focus-visible{outline:3px solid #0071e3;outline-offset:3px}
.sheet{max-width:1000px;margin:0 auto 32px;padding:44px;background:#fff;border:1px solid #e5e5ea;border-radius:20px;box-shadow:0 8px 36px #1d1d1f08;overflow-wrap:anywhere}.report-header{display:flex;justify-content:space-between;align-items:flex-start;gap:24px;padding-bottom:24px;border-bottom:1px solid #d2d2d7}.report-kicker{display:block;color:#0071e3;font-size:10px;font-weight:700;letter-spacing:.16em;margin-bottom:8px}.report-header h1{font-size:28px;letter-spacing:-1px;line-height:1.35;word-break:keep-all;overflow-wrap:anywhere}.report-header p{font-size:12px;color:#6e6e73;margin-top:8px}.report-status{max-width:240px;flex-shrink:0;padding:10px 14px;border:1px solid #d2d2d7;border-radius:12px;background:#f5f5f7;font-size:12px}.report-status span{display:block;font-size:10px;color:#6e6e73;margin-bottom:2px}.report-status b{display:block}.good{color:#24633c;background:#eff8f1;border-color:#c3dfcd}.caution{color:#895415;background:#fff8eb;border-color:#ead2a6}.danger{color:#a62924;background:#fff1ef;border-color:#ebc2bc}.neutral{color:#52525b;background:#f5f5f7;border-color:#d2d2d7}
.summary,.inertia-metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin:24px 0}.summary>div,.inertia-metrics>div{padding:16px;background:#f5f5f7;border-radius:12px;min-width:0}.summary span,.inertia-metrics span{display:block;color:#6e6e73;font-size:11px;margin-bottom:4px}.summary b,.inertia-metrics b{display:block;font-size:20px;line-height:1.4;font-variant-numeric:tabular-nums}.summary small{display:block;font-size:10px;color:#6e6e73;margin-top:4px}.summary .text-metric b{font-size:14px}
.report-nav{display:flex;flex-wrap:wrap;gap:8px 20px;padding:16px 0;border-block:1px solid #e5e5ea;font-size:12px;color:#515157}.report-nav a{text-decoration:none}.report-nav b{color:#0071e3;margin-right:6px}.report-section{margin-top:32px;scroll-margin-top:20px}.report-section-head{display:flex;align-items:flex-start;gap:12px;margin-bottom:18px;break-after:avoid}.report-section-head>span{display:grid;place-items:center;flex:0 0 32px;height:32px;border-radius:10px;background:#eaf3ff;color:#0071e3;font-size:12px;font-weight:700}.report-section-head h2{font-size:20px;letter-spacing:-.5px;line-height:1.4}.report-section-head p{margin-top:4px;color:#6e6e73;font-size:12px}.section-title,.title,.cargo-intake-title{display:flex;justify-content:space-between;align-items:baseline;gap:12px;margin:22px 0 10px;break-after:avoid}.section-title h2,.title h2,.cargo-intake-title h2,h3{font-size:15px}.section-title span,.title span,.cargo-intake-title span{font-size:11px;color:#6e6e73}h3{margin:18px 0 10px;break-after:avoid}
.report-table-scroll{max-width:100%;overflow-x:auto;border:1px solid #dedee3;border-radius:12px;margin:12px 0 18px}table{border-collapse:collapse;width:100%;font-size:12px;line-height:1.55;table-layout:fixed}th,td{padding:11px 10px;text-align:left;vertical-align:top;border-bottom:1px solid #e5e5ea;overflow-wrap:anywhere}th{background:#f5f5f7;color:#515157;font-size:11px;font-weight:650}tbody tr:last-child td{border-bottom:0}tbody tr:nth-child(even){background:#fafafa}td small{display:block;color:#6e6e73;font-size:10px;margin-top:3px}td b{display:block}.group-no,.seq{width:48px;color:#0071e3;text-align:center}.group-no b,.seq b{font-size:18px}.check,.shipment-check{width:44px;text-align:center;font-size:20px}.numeric{font-variant-numeric:tabular-nums}.report-pill{display:inline-block;padding:2px 7px;border:1px solid;border-radius:6px;white-space:nowrap;font-size:10px;font-weight:650}.empty-state{padding:14px 16px;border:1px solid #dedee3;border-radius:10px;background:#fafafa;color:#515157}
.direction,.worker-note,.note,.overall,.notice{padding:14px 16px;margin:14px 0;border-radius:12px;background:#f0f6ff;color:#244b73;font-size:12px;line-height:1.7}.direction{display:flex;flex-wrap:wrap;justify-content:space-between;gap:8px;font-weight:650}.direction em{font-style:normal}.overall b,.overall span{display:block}.overall span{margin-top:5px}.diagram-grid,.diagrams{display:grid;grid-template-columns:minmax(0,1fr);gap:16px}.diagram-grid svg,.diagrams svg{width:100%;height:auto;display:block;border:1px solid #dedee3;border-radius:12px;break-inside:avoid}.progress{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.progress svg{width:100%;height:auto;break-inside:avoid}.legend{font-size:11px;color:#6e6e73;margin:10px 0}
.materials{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.materials>div{border:1px solid #dedee3;border-radius:10px;padding:12px;break-inside:avoid}.materials span,.materials i{display:block;font-size:11px;color:#6e6e73}.materials b{display:block;font-size:15px;margin:4px 0}.materials i{font-style:normal}.recommendations,.recommend{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:12px 0;padding:0}.recommendations li,.recommend li{list-style:none;display:grid;grid-template-columns:24px minmax(0,1fr);gap:10px;padding:12px;border:1px solid #dedee3;border-radius:10px;font-size:12px;break-inside:avoid}.recommendations li b,.recommend li b{display:grid;place-items:center;width:24px;height:24px;background:#f0f6ff;color:#0071e3;border-radius:50%;font-size:11px}.final-check,.final{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin:18px 0}.final-check>div,.final>div{padding:14px 12px;border:1px solid #dedee3;border-radius:10px;font-size:12px;break-inside:avoid}.checklist{list-style:none;padding:0;margin:12px 0}.checklist li{padding:10px 0;border-bottom:1px solid #e5e5ea;font-size:12px;break-inside:avoid}.checklist li::before{content:'□';margin-right:10px;color:#515157}.report-signoff{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px;margin-top:24px;break-inside:avoid}.report-signoff div{min-height:76px;padding:10px 0;border-top:1px solid #d2d2d7}.report-signoff span{display:block;font-size:12px}.report-signoff b{display:block;margin-top:24px;color:#86868b;font-size:10px;font-weight:400}.technical-note,.technical{font-size:11px;color:#6e6e73;margin-top:18px;line-height:1.65}.footer{display:flex;flex-wrap:wrap;justify-content:space-between;gap:8px 20px;margin-top:24px;padding-top:14px;border-top:1px solid #d2d2d7;font-size:10px;color:#6e6e73}.watermark{position:fixed;inset:42% 0 auto;text-align:center;transform:rotate(-18deg);font-size:48px;font-weight:800;color:#b91c1c12;pointer-events:none;z-index:20}
.shipment-block{margin:12px 0 20px}.shipment-head{display:flex;justify-content:space-between;align-items:baseline;gap:12px;margin-bottom:10px}.shipment-head h2{font-size:15px}.shipment-head span{font-size:10px;color:#6e6e73}.shipment-manual,.shipment-meta{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin:12px 0}.shipment-manual>div,.shipment-meta>div{padding:10px;background:#f5f5f7;border-radius:8px;min-width:0}.shipment-manual span,.shipment-meta span{font-size:10px;display:block;color:#6e6e73}.shipment-manual b,.shipment-meta b{font-size:12px;display:block;margin-top:8px}.shipment-fallback{padding:10px 12px;background:#fff8eb;border-radius:8px;font-size:11px;color:#895415}.shipment-ok{color:#24633c}.shipment-warn{color:#a62924}.shipment-direct{color:#654599}.shipment-table th,.shipment-table td{padding:9px 7px;font-size:11px}.shipment-table small{font-size:10px}.cargo-intake-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.cargo-intake-card{display:grid;grid-template-columns:64px minmax(0,1fr);align-items:center;gap:10px;min-width:0;padding:10px;border:1px solid #dedee3;border-radius:10px;break-inside:avoid}.cargo-intake-image svg{width:64px;display:block}.cargo-intake-info>*{display:block}.cargo-intake-info b{font-size:12px}.cargo-intake-info span,.cargo-intake-info small{font-size:10px;color:#6e6e73}.cargo-intake-info strong{font-size:16px;color:#0071e3;margin:3px 0}
.sequence{display:grid;grid-template-columns:1fr 1fr;gap:12px}.sequence article{padding:14px;border:1px solid #dedee3;border-radius:12px;break-inside:avoid}.sequence header{display:flex;justify-content:space-between;gap:10px;border-bottom:1px solid #dedee3;padding-bottom:8px}.sequence header b{font-size:16px;color:#0071e3}.sequence header span{font-size:10px;color:#6e6e73}.sequence p{padding:7px 0;border-bottom:1px dotted #dedee3;font-size:12px}.sequence footer{font-size:10px;color:#6e6e73;margin-top:8px}.history{display:grid;gap:8px}.history>span{padding:12px;border:1px solid #dedee3;border-radius:10px;font-size:11px}.history b{display:block;margin-bottom:3px}.history .pass-step{border-left:3px solid #46865b}.history .fail-step{border-left:3px solid #c28a37}
@media screen and (max-width:700px){.report-toolbar{padding:0 16px;flex-wrap:wrap}.report-toolbar>span{width:100%}.sheet{padding:24px 16px;margin:0;border-radius:0;border-inline:0}.report-header{display:block}.report-header h1{font-size:24px}.report-status{margin-top:16px;max-width:none}.summary,.inertia-metrics{grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.summary>div{padding:12px}.summary b{font-size:18px}.materials,.sequence,.recommendations,.recommend,.final-check,.final,.cargo-intake-grid,.progress{grid-template-columns:1fr}.shipment-manual,.shipment-meta{grid-template-columns:repeat(2,minmax(0,1fr))}.section-title,.title,.shipment-head,.cargo-intake-title{align-items:flex-start;flex-direction:column;gap:4px}.report-table-scroll table{min-width:680px}.report-signoff{gap:10px}.report-nav{gap:10px 16px}.report-section-head h2{font-size:19px}}
@media print{html{scroll-behavior:auto}body{background:#fff;font-size:9pt}.report-toolbar,.report-nav{display:none}.sheet{max-width:none;border:0;border-radius:0;box-shadow:none;padding:0;margin:0}.report-header{padding-bottom:12px;gap:16px}.report-header h1{font-size:20pt}.report-header p{font-size:8pt}.report-kicker{font-size:7pt;margin-bottom:4px}.report-status{font-size:9pt;max-width:58mm;padding:7px 10px}.summary,.inertia-metrics{margin:16px 0;gap:8px}.summary>div,.inertia-metrics>div{padding:10px}.summary b,.inertia-metrics b{font-size:13pt}.summary span,.summary small{font-size:7.5pt}.summary .text-metric b{font-size:10pt}.report-section{margin-top:22px}.report-section-head{margin-bottom:12px}.report-section-head h2{font-size:14pt}.report-section-head p{font-size:8pt}.report-section-head>span{width:26px;height:26px;flex-basis:26px;font-size:9pt}.report-table-scroll{overflow:visible;border-radius:0;border:0;margin:10px 0 14px}table{font-size:8pt;table-layout:fixed}th,td{padding:7px 6px}th{font-size:7.5pt;border-top:1px solid #dedee3}td small,.shipment-table small{font-size:7pt}thead{display:table-header-group}tr{break-inside:avoid}h3,.section-title,.title,.cargo-intake-title,.shipment-head{break-after:avoid}h3,.section-title h2,.title h2,.shipment-head h2,.cargo-intake-title h2{font-size:10pt}.shipment-table th,.shipment-table td{font-size:7.5pt;padding:7px 5px}.shipment-block{break-inside:auto}.materials>div,.sequence article{padding:9px}.materials b{font-size:11pt}.materials span,.materials i,.sequence p,.recommendations li,.recommend li,.final-check>div,.final>div,.checklist li{font-size:8pt}.recommendations li,.recommend li{padding:9px}.worker-note,.note,.notice,.overall,.direction{font-size:8pt;padding:10px 12px}.technical-note,.technical{font-size:7.5pt}.footer{font-size:7pt;margin-top:16px}.report-signoff div{min-height:64px}.report-signoff span{font-size:8pt}.report-signoff b{font-size:7pt}.diagram-grid,.diagrams{gap:10px}.report-header,.summary,.report-section-head,.direction,.overall,.diagram-grid svg,.diagrams svg,.progress svg{break-inside:avoid}.cargo-intake-info b{font-size:8pt}.cargo-intake-info span,.cargo-intake-info small{font-size:7pt}.cargo-intake-info strong{font-size:11pt}.legend{font-size:8pt}.history>span{font-size:8pt}.report-pill{font-size:7pt}}
.report-advisory{max-width:1000px;margin:16px auto;padding:14px 20px;border:1px solid #ead2a6;border-radius:12px;background:#fff8eb;color:#895415;font-size:13px;line-height:1.6}.shipment-head h3,.cargo-intake-title h3,.section-title h3,.title h3{margin:0}.mixed-card{margin:18px 0}.mixed-card>h3{break-after:avoid}
@media print{
  @page{@bottom-right{content:counter(page) ' / ' counter(pages);font:8pt Arial;color:#6e6e73}}
  body{line-height:1.45}.report-section{margin-top:16px}.report-section-head{margin-bottom:9px}
  h3,.section-title,.title,.cargo-intake-title{margin-top:12px;margin-bottom:7px}
  .summary,.inertia-metrics{margin:12px 0}.summary>div,.inertia-metrics>div{padding:8px}
  th,td{padding:6px}.report-signoff{margin-top:16px}.report-signoff div{min-height:54px}.report-signoff b{margin-top:18px}
  .checklist li{padding:7px 0}.technical-note,.technical{margin-top:12px}
  .recommendations li,.recommend li{padding:8px}.direction{break-after:avoid}
  .report-section:last-of-type{break-inside:avoid}
  .report-advisory{margin:0 0 12px;font-size:9pt}
}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}
`;

export function buildReportDocument(doc: ReportDocument) {
  const sections = doc.sections.map((section, index) => `<section class="report-section" id="section-${index + 1}" aria-labelledby="heading-${index + 1}"><header class="report-section-head"><span>${String(index + 1).padStart(2, '0')}</span><div><h2 id="heading-${index + 1}">${reportEscape(section.title)}</h2><p>${reportEscape(section.description)}</p></div></header>${section.content}${index === doc.sections.length - 1 ? `<footer class="footer">${doc.footer}</footer>` : ''}</section>`).join('');
  return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${reportEscape(doc.title)}</title><style>${REPORT_CSS}</style></head><body>
    <div class="report-toolbar"><span>LOAD STUDIO · 화면에서 검토한 후 A4로 인쇄하세요.</span><div><button type="button" onclick="window.close()">닫기</button><button type="button" class="print" onclick="window.print()">인쇄 / PDF 저장</button></div></div>
    ${doc.watermark ? `<div class="watermark" aria-hidden="true">${reportEscape(doc.watermark)}</div>` : ''}
    <main class="sheet"><header class="report-header"><div><span class="report-kicker">LOAD STUDIO / OPERATIONS</span><h1>${reportEscape(doc.title)}</h1><p>${reportEscape(doc.subtitle)}</p></div><div class="report-status ${doc.tone}"><span>현재 검증 상태</span><b>${reportEscape(doc.status)}</b></div></header>
    ${doc.summary}<nav class="report-nav" aria-label="문서 목차">${doc.sections.map((section, index) => `<a href="#section-${index + 1}"><b>${String(index + 1).padStart(2, '0')}</b>${reportEscape(section.title)}</a>`).join('')}</nav>${sections}</main></body></html>`;
}
